kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: webserver-{{.Replica}}-{{.Iteration}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: webserver
        image: quay.io/cloud-bulldozer/sampleapp:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: webserver-{{.Replica}}-{{.Iteration}}
  strategy:
    type: RollingUpdate
