name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
    - "**.md"
    - "examples/**"
    - "hack/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
    - "**.md"
    - "examples/**"
    - "hack/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: [1.16]
        k8s-version:
        - v1.20.0
        - v1.19.0
        - v1.18.0
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.golang-version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache prometheus
      uses: actions/cache@v2
      with:
        path: /prometheus-2.22.0.linux-amd64
        key: prometheus

    - name: Download prometheus
      run: |
        [[ ! -f prometheus-2.22.0.linux-amd64/prometheus ]] && curl -sSL https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz | tar xz

    - name: Run prometheus
      run: |
        pushd prometheus-2.22.0.linux-amd64
        ./prometheus --storage.tsdb.path=/tmp/promdata 2>/dev/null &

    - name: Build
      run: make build

    - name: Install
      run: sudo make install

    - name: Setup kind
      working-directory: test
      run: ./setup-kind.sh
      env:
        KIND_VERSION: v0.11.1
        K8S_VERSION: ${{matrix.k8s-version}}
  
    - name: Execute kube-burner test
      working-directory: test
      run: ./run.sh

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@04eca2038305127fb1e6683425b6864cd5612f2d
      uses: golangci/golangci-lint-action@v2
      with:
        # version of golangci-lint to use in form of v1.2.3
        version: v1.32
        # if set to true and the action runs on a pull request - the action outputs only newly found issues
        only-new-issues: true
        # golangci-lint command line arguments
        #args: # optional, default is 
        # golangci-lint working directory, default is project root
        #working-directory: # optional
        # the token is used for fetching patch of a pull request to show only new issues
        #github-token: # default is ${{ github.token }}

  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: make images

