# image-upload.yml
on:
  workflow_call:
jobs:
  containers:
    name: Build container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - arm64
        - amd64
        - ppc64le
        - s390x

    steps:

      - name: Install dependencies required for multi-arch builds
        run: sudo apt-get update && sudo apt-get install qemu-user-static podman fuse-overlayfs

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          id: go

      - name: Login in quay
        run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Build kube-burner binary
        run: make build
        env:
          ARCH: ${{ matrix.arch }}

      - name: Build container image
        run: make images
        env:
          ARCH: ${{ matrix.arch }}

      - name: Push container image
        run: make push
        env:
          ARCH: ${{ matrix.arch }}

  manifest:
    name: Build container manifest
    runs-on: ubuntu-latest
    needs: containers
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Login in quay
        run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Create and push manifest
        run: make manifest
